select * from (select * from authors inner join authorisbn on authors.AuthorsId=authorisbn.AuthorId) x inner join titles on x.ISBN=titles.ISBN;
select AuthorsID,FirstNAme,LastName,x.ISBN,Title,EditionNumber,Copyright from (select * from authors inner join authorisbn on authors.AuthorsId=authorisbn.AuthorId) x inner join titles on x.ISBN=titles.ISBN;
select * from (select * from authors a left outer join authorisbn i on a.AuthorsID=i.AuthorID) x left outer join titles t on x.ISBN=t.ISBN union select * from (select * from authors a right outer join authorisbn i on a.AuthorsID=i.AuthorID) x right outer join titles t on x.ISBN=t.ISBN order by Title asc;
insert into titles (ISBN,Title,EditionNumber,Copyright) values (123456,'livro6',6,2030);
update titles set Title='livro7' where ISBN=165468;
insert into authors (FirstName,LastName) values ('Viludo','Pinheiro');
insert into authorisbn (AuthorID,ISBN) values (7,546549);
insert into titles (ISBN,Title,EditionNumber,Copyright) values (165468,'ViludoTales',7,2016);
create or replace view myView as select AuthorsID,FirstName,LastName,AuthorID,ISBN,ISBN_2,Title,EditionNumber,Copyright from (select * from authors a join authorisbn b on a.AuthorsID=b.AuthorID) x join (select ISBN as ISBN_2,Title,EditionNumber,Copyright from titles) t on x.ISBN=t.ISBN_2;
select * from myview;
delete authors from authors join authorISBN on authors.AuthorsID=authorISBN.AuthorID where authors.AuthorsID=22;
delete from authors where authors.AuthorsID=31 or authors.AuthorsID=32;
delete authorISBN from authorISBN where authorisbn.AuthorID=31 or authorisbn.AuthorID=32;
delete from titles where titles.isbn='32165' or titles.isbn='79456';
select * from (select * from authors left join authorisbn on authors.AuthorsID=authorisbn.AuthorID) x union (select * from (select * from authors right join authorisbn on authors.AuthorsID=authorisbn.AuthorID) y) order by AuthorsID;

create view pstmt1 as (select * from authors a left outer join authorisbn i on a.AuthorsID=i.AuthorID);
create view pstmt2 as (select * from authors a right outer join authorisbn i on a.AuthorsID=i.AuthorID);
create view pstmt3 as (select AuthorsID,FirstNAme,LastName,x.ISBN as ISBN1,Title,EditionNumber,Copyright from pstmt1 x left outer join titles t on x.ISBN=t.ISBN);
create view pstmt4 as (select AuthorsID,FirstNAme,LastName,y.ISBN as ISBN2,Title,EditionNumber,Copyright from  pstmt2 y right outer join titles t on y.ISBN=t.ISBN);
select * from (select * from pstmt3 union select * from pstmt4) z where z.FirstName like'D%' order by Title asc;
